### ISSUE TITLE
rust ImageSurface get_data panicled!

### ISSUE THREAD

**Issue by toplinuxsir** [gtk-rs/cairo#278] opened 2019-08-10 00:27 UTC
ImageSurface get_data panicled!
First create a ImageSurface and then drawing with some text and lines
and then 
```
let data = surface.get_data().unwrap();

```

at 'called `Result::unwrap()` on an `Err` value: NonExclusive'

**Comment by RazrFalcon** [comment] 2019-08-10 03:49
This is an expected behavior. `ImageSurface::get_data` acts like `Rc::borrow_mut`. You can have only one mutable reference at any point.

**Comment by toplinuxsir** [comment] 2019-08-10 04:25
How to avoid it  ?
Thans !

**Comment by RazrFalcon** [comment] 2019-08-10 04:29
1. Do not use `unwrap`.
2. Make sure that surface isn't used by cairo (usually set via `set_source_surface` or `set_source` woth pattern).

**Comment by toplinuxsir** [comment] 2019-08-12 00:19
set_surce_surface or set source not working , I just want to get the drawed data of byte array to process, But it always return alue: NonExclusive'
Can you show me some example code ? Thanks

**Comment by RazrFalcon** [comment] 2019-08-12 04:17
Can you show your code?

**Comment by sdroege** [comment] 2019-08-12 07:41
Yeah, please provide an example of what you're doing so we can reproduce your problem and suggest a solution.

**Comment by toplinuxsir** [comment] 2019-08-13 01:14
```
pub fn draw_bounding_text(
	ctx: &Context,
	x: f64,
	y: f64,
	txt: &str,
	font_face: &str,
	font_size: f64,
) -> (f64, f64, f64, f64) {
	ctx.set_antialias(Antialias::Best);
	ctx.move_to(x, y);
	ctx.set_source_rgb(0.0, 0.0, 0.0);
	ctx.select_font_face(font_face, FontSlant::Italic, FontWeight::Bold);
	ctx.set_font_size(font_size);
	let exts = ctx.text_extents(txt);
	ctx.show_text(txt);
	ctx.set_line_width(1.0);
	/*ctx.set_source_rgb(1.0, 0.0, 0.0);
	ctx.rectangle(
		x + exts.x_bearing,
		y + exts.y_bearing,
		exts.width,
		exts.height,
	); */
	// ctx.stroke();

	(
		x + exts.x_bearing,
		y + exts.y_bearing,
		exts.width,
		exts.height,
	)
}

pub fn draw() {
	let mut surface =
		ImageSurface::create(Format::Rgb24, 1000, 1000).expect("Unable to create Image");
	let ctx = Context::new(&surface);

	ctx.set_source_rgb(1.0, 1.0, 1.0);
	ctx.paint();

	let barcode = "0OABCDEFGabcdefg1234567";

	let (x1, y1, w1, h1) = draw_bounding_text(&ctx, 100.0, 100.0, barcode, "Ubunut", 30.0);
	draw_bounding_text(&ctx, 100.0, 170.0, barcode, "Fira Code Retina", 30.0);
	draw_bounding_text(&ctx, 100.0, 240.0, barcode, "Ubuntu Mono", 30.0);

	draw_bounding_text(&ctx, 100.0, 310.0, barcode, "SourceCode Pro", 30.0);
	
	surface.flush();

	let data = surface.get_data().unwrap(); // This will panic 
}

```

**Comment by sdroege** [comment] 2019-08-13 06:41
`drop(ctx)` before you access the data. The context also has a reference to the surface.

@GuillaumeGomez can you close this? This is a support request, not a bug.

**Closed** 2019-08-13 08:08 UTC

**Comment by toplinuxsir** [comment] 2019-08-16 00:19
Sorry for late reply , Thanks , I fixed it .
